### ISSUE TITLE
Executors using macOS instead of darwin

### ISSUE THREAD

**Issue by ghost** [VVX7/nicodemus#1]
I could be missing a reference after a quick glance at the executors file - but it looks like its using "macos" instead of "darwin' as the platform name. As a result, I'm getting "no executors found" for Mac TTPs.

**Comment by VVX7** [comment]
Fixed. Nim's `hostOS` const returns 'macosx`. Added `returnPlatform()` to keep hostOS names consistent with operator platform values.
