### ISSUE TITLE
Make compatible for Operator ingestion

### ISSUE THREAD

**Issue by ghost** [VVX7/nicodemus#3]
This agent is a GREAT first agent we'd (Prelude) be interested in making available by default within Operator via the AgentLibrary plugin.

If you'd be willing, we just need to you make 2 changes to this code to make it work:

1. Add a build.sh file at the project root, with the command which will compile the agent into an executable (check Pneuma for an example, for each supported OS).

@khyberspache this is all that needs to be done from the agent-side, correct?

**Comment by VVX7** [comment]
Added `build.sh` that compiles for the current host OS (Linux or MacOS) and additionally cross-compiles to Windows.

Unfortunately, Nim cross-compiling is not as easy as Go's.  Building for MacOS from Linux requires installing the [osxcross](https://github.com/tpoechtrager/osxcross#packaging-the-sdk) toolchain and it's a bit of a journey.

I've linked to this [dockerfile](https://github.com/chrisheller/docker-nim-cross) in the cross-compiling section of the README. It makes cross-compiling easier but I need to test it further.

**Comment by khyberspache** [comment]
I'll need to add in docker support to our build server.

**Comment by khyberspache** [comment]
Working this now, will be bug testing/fleshing out our build pipeline to support this

**Comment by VVX7** [comment]
Thanks!
